name: Deploy Astro Site

on:
  push:
    branches:
      - main # Change this to your main branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 14 # You can specify the Node.js version you need

    - name: Install Dependencies
      run: npm install

    - name: Build Astro Site
      run: npm run build

    - name: Copy Files to Server
      uses: appleboy/scp-action@v0.3
      with:
        host: ${{ secrets.SERVER_IP }}
        username: ${{ secrets.SSH_USERNAME }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        source: "Sui.chainflow/dist" # Change this to the actual build output folder
        target: "/var/www/html"

