name: Build and Deploy

on:
  push:
    branches:
      - main # Change this to the branch you want to trigger the workflow

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 14 # Change to your desired Node.js version

    - name: Install dependencies
      run: npm install

    - name: Build
      run: npm run build

    - name: Deploy to server
      run: |
        scp -r ./dist/* :/var/www/html/
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
